name: Go

on: [push]

jobs:
  build:
    # runs on a older version of Ubuntu, so that we get
    # a GLIBC version that has better compatibility
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5 # this actually brings build caches by default, nice!
        with:
          go-version: '1.23.4'
          check-latest: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libpam0g-dev

      - name: Build
        run: ./build.sh

      - name: Upload Main Executable
        uses: actions/upload-artifact@v4
        with:
          name: bb
          path: ./bin/bb

      - name: Upload the bin Folder for debugging
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: ./bin